### ISSUE TITLE
Nice thing, but lot of issue to configure it

### ISSUE THREAD

**Issue by maxlehot1234** [christopwner/zabbix-hue-alertscript#1]
Hi, I just download your script and install it on my zabbix linux server and I am able to get a user token from philips hue.

But after I setup the media type, what I need to do? Create an action? How and which informations I need to make my hue bulb to flash?

Also, is it possible to create a custom action depends of the host? So each host will have a light associated to it to create a much better experience?

Thanks in advance,

**Comment by christopwner** [comment]
Hi @maxlehot1234 I believe you are correct. After setting up your items, triggers, and new mediatype w/ script, you'll need to create an action to send out the notification when the trigger fires off. See https://www.zabbix.com/documentation/4.0/manual/config/notifications/action

Be aware that I've only tested this on Zabbix 4.0, not sure what has changed in 5.0

**Comment by maxlehot1234** [comment]
I still use zabbix 4.x :)

Related the action, zabbix ask me to choose a message and everything. They are technically not needed since we simply a light right?

A mini-tutorial will be really appreciate if you have one that allow us to setup everything little bit easier ;)

Thanks for the reply

**Comment by christopwner** [comment]
I think the action messages are stored in history so it may help to have them even if they aren't being sent out to the hue. Unfortunately I dont have access to the system i set this up for originally so no way for me to quicky test or look at previous configuration. 😞

**Comment by maxlehot1234** [comment]
Ok I will try to test few things on my end. Thanks again for your help.

So if I understand correctly, I can technically put anything in the action and "link it" to the message type. The message, text and everything will be use in the notification logs as example?

Anyway, I already receive IOS notifications and emails ;)

**Comment by sgevents-sam** [comment]
Used this as a great starting point to get some hue integration into zabbix. 

Refined version available here: 
https://github.com/sgevents-sam/zabbix_hue_triggers

**Comment by christopwner** [comment]
awesome, glad it helped @sgevents-sam :+1:
